# encoding: utf-8
head_list = ["项目编号", "项目简称", "项目名称", "项目负责人", "负责部门", "客户名称", "业务城市", "公司主体", "合同类型", "项目类别", "起始日期", "终止日期",
             "目前状态", "客服专员", "客服主管", "外包主管", "客服经理",
             "其他负责人", "参保地", "社保险种", "社保账户类型", "社保账户名称", "社保节点要求",
             "社保结算周期（月/日）", "商保公司",
             "商保结算周期（年/月/日）", "商保收取标准", "商报赔付额度", "商保节点要求", "公积金地点",
             "比例", "基数", "服务费标准", "服务费节点要求", "残保金收取周期（年/月/日）", "残保金收取地",
             "提供结算表时间(2016-01-01)",
             "费用到账时间(2016-01-01)",
             "工资发放时间(2016-01-01)",
             "工资发放方式", "结算对接人和联系方式", "异常结算情况", "工资服务结算周期", "其他需要我司代收代付项目", "发票抬头", "开票方式", "专票科目", "专票费用内容",
             "专票说明", "普票科目", "普票费用内容", "普票说明", "发票接收人", "电话", "地址", "快递说明", "发票开具日期(2016-01-01)",
             "是否一般纳税人(是 / 否)", "纳税人识别号", "地址", "电话", "开户行", "账号", "销售人员", "销售类型", "派遣提成标准", "备注", "外包提成标准",
             "备注",
             "代理人事提成标准", "备注", "代理招聘提成标准", "备注", "小时工提成标准", "备注", "招聘难度系数", "1月", "2月", "3月", "4月", "5月", "6月",
             "7月", "8月", "9月", "10月", "11月", "12月"
             ]
print len(head_list)
field_list = [
    "number",
    "short_name",
    "full_name",
    "principal",
    "department",
    "customer",
    "business_city",
    "company_subject",
    "contract_type",
    "project_type",
    "start_date",
    "end_date",
    "progress_state",
    "customer_service_staff",
    "customer_service_charge",
    "outsource_director",
    "customer_service_director",
    "other_responsible_person",
    "insured_place",
    "social_security_type",
    "social_security_account_type",
    "social_security_account_name",
    "social_security_node_require",
    "social_security_settlement_cycle",
    "business_insurance_company",
    "business_insurance_settlement_cycle",
    "business_insurance_standard",
    "business_insurance_payment",
    "business_insurance_node_require",
    "accumulation_fund_place_province",
    "proportion",
    "radix",
    "service_standard",
    "service_cost_node_require",
    "residual_premium_cycle",
    "residual_premium_place",
    "settlement_report_day",
    "cost_arrival_day",
    "wage_grant_day",
    "wage_grant_type",
    "settlement_person",
    "abnormal_settlement",
    "wage_service_cost_settlement_cycle",
    "other_project",
    "invoice_type",
    "invoice_title",
    "invoice_mode",
    "special_subject",
    "special_cost",
    "special_desc",
    "general_subject",
    "general_cost",
    "general_desc",
    "invoice_receiver",
    "invoice_phone",
    "invoice_mail",
    "fast_mail_desc",
    "invoice_open_date",
    "is_general_taxpayer",
    "taxpayer_identifier",
    "address",
    "phone",
    "bank",
    "account_number",
    "salesman",
    "sales_type",
    "dispatch_commission",
    "remark1",
    "outsourc_commission",
    "remark2",
    "proxy_personnel_commission",
    "remark3",
    "proxy_recruitment_commission",
    "remark4",
    "hourly_commission",
    "remark5",
    "recruit_difficulty",
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
]
print len(field_list)